package runtime

import "embed"

//go:embed web/*
var webFS embed.FS

var presets = []Preset{
	makePreset("animal-kingdom", "Animal Kingdom", "Turn people into expressive dressed animals.", "convert each original person into a matching storybook animal counterpart of the same age and role while preserving who is holding whom, who is standing where, and the exact group arrangement", "tailored animal features, expressive eyes, stylized fur, themed outfits, playful props, cinematic color, and a rich illustrated world", 0.60, 4.8),
	makePreset("superhero-squad", "Superhero Squad", "Transform the scene into a comic-book hero team.", "reimagine each original subject as the same person in superhero form, keeping the exact pose, facial direction, and placement in the photo", "signature hero costumes, glowing powers, dramatic skies, kinetic energy, bold emblem design, action-movie lighting, and splash-page intensity", 0.62, 4.9),
	makePreset("pirate-crew", "Pirate Crew", "Make the whole photo feel like a swashbuckling adventure.", "turn the same subjects into a pirate crew while keeping the same physical relationships, body positions, and overall composition", "weathered coats, treasure maps, ropes, brass details, sea spray, wooden ships, stormy light, and adventurous cinematic worldbuilding", 0.61, 4.8),
	makePreset("dragon-riders", "Dragon Riders", "Epic fantasy riders with dragons and sky drama.", "transform the same people into dragon riders or dragon-tamer heroes, preserving the original number of people, pose structure, and who occupies each part of the frame", "ornate leather armor, windswept capes, dragon scale textures, cloud kingdoms, glowing skies, and epic fantasy spectacle", 0.63, 5.0),
	makePreset("space-explorers", "Space Explorers", "Launch the photo into a vivid sci-fi mission.", "restage the same subjects as interstellar explorers while preserving their identity, placement, pose, and the camera perspective of the source photo", "sleek space suits, glowing controls, starfields, planet light, spaceship interiors, polished sci-fi materials, and high-end adventure-cinema mood", 0.61, 4.8),
	makePreset("merfolk-lagoon", "Merfolk Lagoon", "Swap the scene into a magical underwater world.", "turn the same people into merfolk or underwater adventurers without changing who appears in the image or how they are arranged", "shimmering scales, flowing aquatic fabrics, coral palaces, refracted sunlight, bubbles, tropical sea life, and luminous undersea fantasy", 0.59, 4.7),
	makePreset("robot-republic", "Robot Republic", "Everyone becomes polished cinematic robots.", "transform the same subjects into robot or android versions of themselves while preserving their expressions, positions, and group layout", "refined mechanical faces, brushed metal, LED accents, futuristic city design, glossy machinery, atmospheric haze, and premium sci-fi production design", 0.62, 4.9),
	makePreset("wizard-school", "Wizard School", "Convert the photo into magical academy life.", "turn the same subjects into wizards or magical students, keeping the same count, the same pose structure, and the same subject relationships", "enchanted robes, spellbooks, floating lights, candlelit halls, glowing runes, magical architecture, and cozy grand fantasy atmosphere", 0.58, 4.7),
	makePreset("royal-court", "Royal Court", "Give the scene a lavish palace-movie makeover.", "reimagine the same subjects as royalty or palace figures while keeping the same composition and preserving recognizable facial identity", "embroidered fabrics, gemstone jewelry, gilded interiors, velvet textures, ornate lighting, regal posture, and luxurious historical fantasy styling", 0.58, 4.7),
	makePreset("samurai-clan", "Samurai Clan", "Turn the moment into a cinematic warrior tableau.", "transform the same subjects into samurai or clan figures while preserving the same stance, framing, and person-to-person arrangement", "layered armor, silk garments, banners, lacquered steel, drifting petals, moody weather, and elegant epic Japanese-cinema styling", 0.60, 4.8),
	makePreset("wild-west", "Wild West", "Recast the photo as a frontier adventure.", "turn the same subjects into frontier characters while preserving the exact composition, body language, and overall scene layout", "dusty streets, leather gear, hats, horses, saloon details, desert sunsets, rugged textures, and painted adventure-poster drama", 0.59, 4.7),
	makePreset("ancient-egypt", "Ancient Egypt", "Convert the scene into a golden desert epic.", "restyle the same subjects as figures from ancient Egypt without changing how many subjects are present or where they appear in the frame", "gold adornments, linen drapery, carved stone, desert sunlight, temple murals, ceremonial props, and mythic historical grandeur", 0.57, 4.6),
	makePreset("dinosaur-safari", "Dinosaur Safari", "Drop the photo into a prehistoric expedition.", "transform the same subjects into explorers in a dinosaur world while preserving the original people, pose layout, and photo angle", "prehistoric jungle scale, rugged gear, giant reptile presence, misty foliage, muddy terrain, adventure lighting, and blockbuster survival energy", 0.62, 4.9),
	makePreset("fairy-grove", "Fairy Grove", "Make the scene feel tiny, magical, and enchanted.", "turn the same subjects into woodland fairies or forest spirits while preserving their exact count, body positions, and emotional tone", "glowing wings, mossy textures, oversized flowers, dew sparkle, magical light beams, hidden forest homes, and dreamy nature fantasy", 0.58, 4.7),
	makePreset("alien-market", "Alien Market", "Transform the photo into a bustling off-world bazaar.", "recast the same subjects as alien traders or travelers while preserving who appears where and keeping the same overall composition", "bioluminescent signs, unusual species design, layered fabrics, exotic food stalls, sci-fi clutter, neon haze, and crowded galactic-market atmosphere", 0.63, 4.9),
	makePreset("monster-movie", "Monster Movie", "Give everyone a practical-FX creature makeover.", "transform the same subjects into movie monsters or creature-feature stars without replacing them with different people or changing the scene structure", "prosthetic-style creature design, fangs, scales, horns, eerie lighting, fog, practical-effects texture, and cinematic horror-fantasy polish", 0.62, 4.9),
	makePreset("noir-detectives", "Noir Detectives", "Turn the scene into a moody black-and-neon mystery.", "reimagine the same subjects as noir characters while keeping the same framing, same people, and same physical arrangement", "rainy reflections, trench coats, smoky interiors, hard shadows, neon signs, dramatic spotlighting, and stylish mystery-thriller atmosphere", 0.57, 4.6),
	makePreset("candy-carnival", "Candy Carnival", "Make the whole world look edible and playful.", "transform the same subjects into candy-world versions of themselves while preserving the original composition and subject count", "frosting textures, taffy color, striped tents, jelly shine, candy props, saturated sweetness, and joyful dreamlike spectacle", 0.63, 4.9),
	makePreset("cyberpunk-night", "Cyberpunk Night", "Push the photo into a neon future city.", "turn the same subjects into cyberpunk characters while preserving the exact shot, placement, and composition of the source photo", "glowing signage, chrome fabrics, wet pavement, holograms, layered city clutter, magenta-cyan light, and sharp futuristic nightlife mood", 0.61, 4.8),
	makePreset("jungle-idols", "Jungle Idols", "Convert the scene into a lost-temple adventure.", "restyle the same subjects as explorers or guardians in a jungle ruin while preserving pose, framing, and subject relationships", "mossy stone, carved idols, golden relics, humid light, tangled vines, cinematic adventure framing, and expedition-story atmosphere", 0.60, 4.8),
	makePreset("balloon-parade", "Balloon Parade", "Turn everything into glossy inflatable spectacle.", "transform the same subjects and same scene into balloon-art versions while preserving the exact composition and proportions of the original shot", "inflated shapes, reflective latex, giant parade forms, bright festival color, playful scale, and cheerful sculptural fantasy", 0.64, 5.0),
	makePreset("lego-world", "Lego World", "Convert the photo into a premium brick-built universe.", "turn the same subjects into recognizable Lego versions of themselves while preserving the same composition, gestures, and placement", "glossy plastic surfaces, toy-scale sets, modular architecture, molded accessories, collectible display lighting, and polished brick-diorama charm", 0.64, 5.0),
	makePreset("claymation", "Claymation", "Handmade stop-motion energy with big personality.", "transform the same subjects into stop-motion clay characters while preserving the same people, same pose, and same scene structure", "thumb-pressed clay texture, sculpted props, miniature sets, toy-stage lighting, handcrafted surfaces, and premium stop-motion charm", 0.60, 4.8),
	makePreset("felt-puppets", "Felt Puppets", "Remake the photo as a stitched puppet show.", "turn the same subjects into felt puppets or plush characters while preserving the original count, placement, and body language", "stitched seams, wool textures, button details, soft fabric folds, miniature set dressing, cozy studio light, and tactile handmade personality", 0.61, 4.8),
	makePreset("pixel-art", "Pixel Quest", "Restyle the scene as a bold playable game world.", "convert the same subjects and same scene into a retro game version while preserving the shot composition and who occupies each position", "chunky pixels, curated palette, tile-based environments, crisp silhouettes, game-ui clarity, retro fantasy adventure mood, and polished 16-bit art direction", 0.65, 5.0),
	makePreset("stained-glass", "Stained Glass", "Make the image glow like a fantasy window.", "translate the same subjects and same composition into stained-glass storytelling shapes rather than inventing a new scene", "lead outlines, jewel-tone glass, cathedral glow, decorative symmetry, radiant backlight, and luminous handcrafted pattern design", 0.56, 4.6),
	makePreset("storybook-castle", "Storybook Castle", "Turn the scene into a fairy-tale picture book.", "reimagine the same subjects as fairy-tale characters while preserving recognizable faces, pose, composition, and relationships", "painted castle worlds, glowing skies, whimsical props, soft magical light, illustrated detail, and rich classic fairy-tale atmosphere", 0.58, 4.7),
}

func makePreset(id, name, tagline, subjectShift, worldDetails string, strength, guidance float64) Preset {
	return Preset{
		ID:             id,
		Name:           name,
		Tagline:        tagline,
		Prompt:         restylePrompt(name, subjectShift, worldDetails),
		NegativePrompt: "",
		Strength:       strength,
		Guidance:       guidance,
		Steps:          7,
	}
}

func restylePrompt(styleName, subjectShift, worldDetails string) string {
	return "Restyle this exact photo as " + styleName + ". Keep the same people, same baby or adult relationships, same pets, same pose, same hand placement, same camera angle, same crop, and same composition. Do not add people, remove people, or replace anyone with different strangers. " +
		"If there are people, " + subjectShift + ". If it is a place, pet, object, or landscape, restyle that same scene instead of inventing a new one. " +
		"Change the world, costume, materials, textures, lighting, color, and atmosphere with " + worldDetails + ". Make it clearly transformed, but still obviously the same original photo."
}
